FROM node:16.16-slim as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --force
COPY bundles-src bundles-src/
RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
