FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
    libpq-dev gcc zlib1g-dev libjpeg-dev libpng-dev && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY .. .
CMD ["gunicorn", "-w", "3","-b", "0.0.0.0:8000","star_burger.wsgi:application"
]
