# Generated by Django 5.1.6 on 2025-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('unspecified', 'не указан'), ('cash', 'наличные'), ('money transfer', 'денежный перевод'), ('cards', 'картой')], db_index=True, default='unspecified', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
