# Generated by Django 5.1.6 on 2025-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'необработанный'), (1, 'на кухне'), (2, 'в пути'), (3, 'доставлен')], db_index=True, default='unprocessed', max_length=50, verbose_name='статус заказа'),
        ),
    ]
